<?php
/**
 * @file
 * Code for the NYULMC OOD Content Type Funds List feature.
 */

include_once 'nyulmc_ood_content_type_funds_list.features.inc';


function nyulmc_ood_content_type_funds_list_form_funds_list_node_form_alter(&$form, &$form_state, $form_id){

  $singlteton_exists = nyulmc_ood_core_node_type_exists('funds_list', $form['nid']['#value']);

  if($singlteton_exists){

    drupal_set_message(t('A published Funds List page already exists. <a href="' . base_path() . 'node/' . $singlteton_exists . '/edit">Click here</a> to edit that node.'), 'warning');

    drupal_set_message(t('If you publish a new Funds List page, the existing version will be unpublished.'), 'warning');

  }
}
