<?php
/**
 * @file
 * Code for the NYULMC OOD Content Type Vilcek Hall feature.
 */

include_once 'nyulmc_ood_content_type_vilcek_hall.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nyulmc_ood_content_type_vilcek_hall_form_vilcek_hall_node_form_alter(&$form, &$form_state, $form_id) {

  $singlteton_exists = nyulmc_ood_core_node_type_exists('vilcek_hall', $form['nid']['#value']);

  if($singlteton_exists){

    drupal_set_message(t('A published Vilcek Hall page already exists. <a href="' . base_path() . 'node/' . $singlteton_exists . '/edit">Click here</a> to edit that node.'), 'warning');

    drupal_set_message(t('If you publish a new Vilcek Hall page, the existing version will be unpublished.'), 'warning');

  }
}
